# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f264b182467f5b42064811e60967d4c66c176d46539e444edf4e22475d047abe34dd2d2308595afe714e543321ea848425fe1720fa5f30b0e642e2fda4cf51a

test:
  secret_key_base: 041227327389286ab967e6d221f91c9a2a31f2eb2f89278097aa3b9a14efc10190202bce627f05fb957855300399259500c9558820c5a187656dcb2d13d6d05b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
